lib/download-asset.js, lib/run-contentful-export.js, lib/usageParams.js, package.json, test/download-asset-test.js
=> Add option to also download a space's assets during export

dist/run-contentful-export.js, lib/run-contentful-export.js
=> issue #15: use indent option

README.md
@Khaledgarbaya Just some small changes to the read me for consistency, mostly as I am working on our best practices for space syncing.
=> Small consistency changes to read me

dist/usageParams.js, lib/run-contentful-export.js, lib/usageParams.js, package.json
fixes https://github.com/contentful/contentful-export/issues/23
=> Fix drafts

README.md, lib/index.js
=> fix library usage

bin/contentful-export, lib/index.js, package.json, yarn.lock
closes #11 
**Hint:** The screenshots are slightly out of date (table header wording)
=> Add summary report and duration to the end of the export

package.json
Adding features introduced in https://github.com/contentful/contentful-batch-libs/pull/107
=> feat(createClient): enable headers config

lib/index.js, test/index-test.js, yarn.lock
fixes https://github.com/contentful/contentful-export/issues/53
=> fix(runContentfulExport): return the response object back

README.md, lib/index.js, lib/parseOptions.js, lib/usageParams.js, package.json, yarn.lock
Adds proxy support by passing the config to [axios](https://github.com/mzabriskie/axios)
=> add proxy support

test/unit/proxy-test.js
Make coverage happy again, This PR adds test to the proxy logic.
=> test(proxy): Add proxy test

package.json
This PR will fix the install issue on windows
=> fix: Fix Broken dep on windows

README.md, lib/index.js, lib/parseOptions.js, lib/usageParams.js, package.json
=> Feat: Adding query support + content-only export

README.md
=> docs(README): document querying more clearly

lib/index.js, package.json
Fixes https://github.com/contentful/contentful-export/issues/84
=> fix(logging): do not throw error when creating log file

package.json
Security update for moment:
https://nodesecurity.io/advisories/532
=> fix: Update moment.js dependency

lib/index.js, lib/parseOptions.js, lib/tasks/get-space-data.js, lib/usageParams.js, package.json, test/integration/export-cli.test.js, test/integration/export-lib.test.js, test/unit/parseOptions.test.js, test/unit/tasks/get-space-data.test.js
=> feat(environments): add support to export environments

package.json
This PR removes the warning when the tool is installed
=> fix: Remove warning on install

README.md, lib/index.js, lib/parseOptions.js, lib/tasks/get-space-data.js, test/unit/index.test.js, test/unit/parseOptions.test.js, test/unit/tasks/get-space-data.test.js
=> feat(skipEditorInterfaces): Add flag to skip exporting editor interfaces

lib/index.js, test/unit/index.test.js
=> fix(deps): Do not promisify new mkdirp

.gitignore, lib/tasks/download-assets.js, lib/utils/embargoedAssets.js, package-lock.json, package.json, test/unit/tasks/download-assets.test.js
Currently, the exporter cannot download embargoed assets. This PR adds the capability.
=> Add support for downloading embargoed assets

.eslintrc.js, README.md, babel.config.json, lib/parseOptions.js, package-lock.json, package.json, test/unit/parseOptions.test.js
Add a standard sequence header to outgoing requests.
=> feat(headers): add standard header

types.d.ts
Pretty self-explanatory - there are a couple of types that I missed when initially adding types.
=> Further refinements to add missing types

types.d.ts
Resolves: https://github.com/contentful/contentful-export/issues/966
=> fix(types): fix typo in types.d.ts file

package-lock.json, package.json
Updates contentful-batch-libs to latest to fix date-fns issue
=> chore(deps): update contentful-batch-libs to v9.4.1

lib/index.js
see https://github.com/cli-table/cli-table3/blob/master/basic-usage.md#basic-usage---disable-colors---used-often-in-the-examples-and-tests
=> fix: remove ANSI color codes from table output for better CI/CD compat [ZEND-4747]

package-lock.json, package.json
Reverts contentful/contentful-export#1878
=> Revert "build(deps): bump bfj from 8.0.0 to 9.0.1"

lib/tasks/get-space-data.js, package-lock.json, package.json, test/integration/export-lib.test.js, test/unit/tasks/get-space-data.test.js
bump cma to fix locale paged fetching
=> fix: get all locale data [ZEND-5557]

.circleci/config.yml, package-lock.json, package.json
=> fix: audit fix [EXT-5917]

.github/dependabot.yml, package-lock.json, package.json
- downgrade semantic release again
- update dependabot config
=> chore: fix dependabot downgrade semantic-release again [EXT-5917]
