contentful/contentful-export

README.md, dist/run-contentful-export.js, dist/usageParams.js, lib/run-contentful-export.js, lib/usageParams.js, package.json
Depends on https://github.com/contentful/contentful-batch-libs/pull/73
=> feat(contentful-export): Make limit configurable

README.md, dist/run-contentful-export.js, dist/usageParams.js, lib/run-contentful-export.js, lib/usageParams.js, package.json
This change is exposing a `host` config variable to be able to tell the tool to use a different host instead of the default one for example `preview.contentful.com` to be able to export also Drafts.
This could introduce a Breaking change in the tool.
TODO :
=> [WIP] feat(usageParams): Add host param to be able to use preview api

README.md, lib/usageParams.js
This pull request will add the possibility to the export tool user to adjust the rate limit i.e how many requests per period of time to be sent to Contentfuk
=> feat(contentful-export): add rate limit options

lib/usageParams.js
This PR adds the possibility to specify the API host, this is useful for example if we want to test against staging for example.
The property `managementHost` is coming from [here](https://github.com/contentful/contentful-batch-libs/blob/master/lib/utils/create-clients.js#L40)
=> feat(contentful-export): Add api host option

lib/utils/proxy.js
[`options.httsAgent`](https://github.com/contentful/contentful-export/blob/master/lib/parseOptions.js#L56) needs to be an `httpsAgent` and not a `{httpsAgent: agent}` object
=> fix(proxy): Fix httpsAgent Creation

README.md, lib/index.js, lib/usageParams.js, package.json
This PR is splitting `--query` into `--query-entries` and `--query-assets`
=> feat: seperate querying for entries and assets

README.md, lib/download-asset.js
This is the officially supported non breaking API.
Tested on node 9.2.0
=> use file.end() instead of file.close()

README.md, lib/index.js, lib/parseOptions.js, lib/tasks/get-space-data.js, lib/usageParams.js, test/unit/parseOptions.test.js, test/unit/tasks/get-space-data.test.js
fixes #123 so `--include-drafts` only includes draft entries (and not archived entries) and adds `--include-archived` to include archived entries
=> add `--include-archived` option

.gitignore, .travis.yml, package-lock.json, package.json
Updated `https-proxy-agent` dependency due to [vulnerability](https://www.npmjs.com/advisories/1184) and added `package-lock.json` file.
=> fix(dependency): Update https-proxy-agent dependency

bin/contentful-export, lib/tasks/download-assets.js, lib/tasks/get-space-data.js, test/unit/tasks/get-space-data.test.js
The `npm run lint` command throws errors in a local setup on master and demands changes. Those are the changes applied via the eslint `--fix` option.
=> chore(linter): fix eslint issues to enable npm lint cmd again

example-config.json, example-config.test.json, test/unit/index.test.js, test/unit/parseOptions.test.js
I used [lib/usageParams.js](https://github.com/contentful/contentful-export/blob/master/lib/usageParams.js) and the Readme as a reference.
Most options are set to default or default behaviour (e.g. `downloadAssets` is undefined by default, but there's a truthy check in the code)
=> chore(docs): Add all options to example-config.json

README.md, lib/parseOptions.js, lib/usageParams.js, lib/utils/headers.js, test/unit/parseOptions.test.js, test/unit/utils/headers.test.js
Added _explicit_ support for passing `headers` option down to `contentful-management`. 
A similar option/flag will be added to other related libraries as well (e.g. `contentful-import`).
=> feat: add custom headers support

package-lock.json, package.json
When installing the `node_modules` for this project, there are various out of data packages being installed that are unused. These out of date packages are then causing installation warnings and package bloat for this project - so lets remove them 😄 
- `babel-core` has been superseded by `@babel/core` (already in this project)
- `travis-deploy-once` is clearly not being used in this project, as it is using CircleCI.
**NOTE: All remaining audit security vulnerabilities are related to the `cz-conventional-changelog`**. It seems like this project is being no longer maintained - perhaps we should consider finding an alternative 🤷  
```bash
npm WARN deprecated travis-deploy-once@5.0.11: We recommend to use Travis Build Stages instead
npm WARN deprecated @babel/polyfill@7.6.0: 🚨 This package …
```
=> fix(chore): remove unused dependencies

test/unit/parseOptions.test.js
Unit tests fail on Win10 due to expected Unix path separators (`/`) rather than windows path separators (`\\`).
This PR adds a cross platform method to support constructing regular expressions irrespective of system's path separators. 
Supporting image:
=> fix(test): modify unit tests to handle cross platform absolute path regex matching

lib/tasks/download-assets.js, lib/utils/embargoedAssets.js, package-lock.json, package.json
[Request is deprecated](https://github.com/request/request-promise#deprecated) and is no longer being actively supported.
This PR is to replace `request.js` with `node-fetch`. I selected `node-fetch` as it appears that this will become part of the node standard lib, with experimental support in node18 (see this for more info: https://nodejs.org/en/blog/announcements/v18-release-announce/#fetch-experimental).
This change will also resolve the following npm installation warnings:
```bash
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated mkdirp@0.5.4: Legacy …
```
=> feat(client): replace request with node-fetch

lib/tasks/download-assets.js, package-lock.json, package.json, test/unit/tasks/download-assets.test.js
- Replaces additional package `fs-extra` with node's standard library `fs`.
=> chore(refactor): replace fs-extra with node fs standard library

lib/index.js, package-lock.json, package.json, test/unit/tasks/get-space-data.test.js
**TLDR**: Removes `lodash` package to reduce package bloat.
Lodash is currently being used in 2 locations in this project:
1. In the test suite to generate `n` paginated entries (using `times` function)
2. In the results table to format headers (using `startCase`)
This PR replaces these locations by:
1. Using https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore, replaces `times` function with `Array.from`
2. Removes `lodash` import, replacing it with `lodash.startcase`. This will only import required files and not the whole `lodash` library.
=> chore(deps): remove lodash

.eslintrc, package-lock.json, package.json, test/unit/index.test.js, test/unit/mocks/download-assets.js, test/unit/mocks/get-space-data.js, test/unit/parseOptions.test.js
With the latest lint changes, I noticed the `*.test.js` files no longer were being linted. This PR reintroduces linting for test files, and fixes any issues that arose.
I took this opportunity to tidy up the main unit test file, by:
- Moving large mocked objects into a new `mocks` directory
- Converting tests to async/await syntax (moving away from promise chains)
=> chore(lint): fix eslint for *.test.js files

.github/dependabot.yml
Ignore figures package (>=4.0.0) in depenadabot because it's a pure ESM package.
=> chore(dependabot): Ignore figures package

lib/index.js, lib/parseOptions.js, package-lock.json, package.json, test/unit/parseOptions.test.js
Moment.js is a great library however due to the way it is packaged, it is quite large to install and causes package bloat. This PR replaces moment.js with another popular date parsing library [date-fns](https://www.npmjs.com/package/date-fns). Taken with a grain of salt, it seems like this will reduce package size by a significant amount whilst improving performance (see supporting [article](https://blog.bitsrc.io/date-fns-vs-momentjs-9833f7463751#:~:text=MomentJS%20package%20size%20is%20around,package%20size%20is%20300%20Bytes.)).
=> chore(deps): replace moment with date-fns

lib/index.js, lib/parseOptions.js, lib/tasks/download-assets.js, lib/tasks/get-space-data.js, lib/tasks/init-client.js, package-lock.json, package.json, test/unit/index.test.js, test/unit/parseOptions.test.js, test/unit/tasks/init-client.test.js, test/unit/utils/headers.test.js
- Updates `contentful-batch-libs ` to latest
- General `import` statement fixes. This includes auto-formatting the ordering (VSCode using ALT+SHIFT+O, or CMD+SHIFT+O)
=> chore(deps): update contentful batch libs to latest

lib/tasks/get-space-data.js, test/integration/export-lib.test.js
When passing `deliveryToken` as option and internally using the cdaClient, we don't return even public tags. This should be adjusted, as it causes imports based on public tags to fail.
- Should we export all tags here even if deliveryToken is passed in?
- Should we only export public tags?
Starting points to look at:
- Initialization of cdaClient: https://github.com/contentful/contentful-export/blob/feat%2Fexport-public-tags/lib/tasks/init-client.js#L25
- Introduction of tags on the cma: https://github.com/contentful/contentful-export/commit/e79a35caf7b4dff6d9864cdbf7280ded89486b8c
=> feat(public-tags): export public tags

lib/utils/embargoedAssets.js, test/unit/tasks/download-assets.test.js, test/unit/utils/embargoedAssets.test.js
Fixes a bug, as the current implementation would never cache at all (as `cacheItem.expiresAtMs < minExpiresAtMs` is always true). 
With this change, we will only create new cacheItems if the time difference between the last cachedItem expiry time and the current key expiry time is greater than 6 hours.
This is where download support for embargoed assets and the caching logic was introduced: https://github.com/contentful/contentful-export/pull/680
=> fix(asset-cache): embargoed assets cache calculation

lib/tasks/get-space-data.js, lib/tasks/init-client.js, package-lock.json, package.json, test/unit/tasks/init-client.test.js
These tweaks allow us to upgrade contentful.js
I came to these conclusions via these error messages:
```
[Error: ValidationError: Invalid "resolveLinks" provided, The use of the 'resolveLinks' parameter is no longer supported. By default, links are resolved. If you do not want to resolve links, use client.withoutLinkResolution.]
[Error: ValidationError: Invalid "locale" provided, The use of locale='*' is no longer supported.To fetch an entry in all existing locales, use client.withAllLocales instead of the locale='*' parameter.]
```
=> chore: updates to allow usage of newer cda client []

types.d.ts
skipTags is missing in the types...
=> fix: 'skipTags' missing in Options

README.md, lib/tasks/init-client.js, lib/usageParams.js
Allows the hostDelivery option to be used to point the export at cdn.eu.contentful.com when a deliveryToken is used to export entries from the CDA
=> fix: allow host-delivery config to be passed to export command [EXT-5986]

lib/parseOptions.js, lib/tasks/init-client.js, package.json, test/unit/tasks/init-client.test.js
Pass through all SDK config options (namely `httpAgent` and `httpsAgent`) when using the CDA to export
fixes: https://github.com/contentful/contentful-export/issues/1821
=> feat: support all sdk config options when using CDA

lib/tasks/download-assets.js
This PR fixes an issue when using the `useVerboseRenderer` option, the asset name is showing up as "unknown"
before fix:
```
[14:11:13] Download assets [started]
[14:11:13] → ✔ downloaded unknown (//images.ctfassets.net/.../image.png)
```
after fix:
```
[14:34:44] Download assets [started]
[14:34:44] → ✔ downloaded image.png (//images.ctfassets.net/<space_id>/<etc>/.../image.png)
```
=> fix: asset name in logs [ZEND-5790]

lib/tasks/download-assets.js
Need a small adjustment to ensure assets downloaded via the axios client are saved correctly - in particular, we adjust the response type to be stream instead of blob and ensure that no transformations are made to the data stream
=> fix: asset download using axios [ZEND-5790]

README.md
Add instructions in the `Troubleshooting` section for how to use `contentful-export` and `contentful-import` with embargoed assets. See equivalent PR in `contentful-import` here: https://github.com/contentful/contentful-import/pull/1398
=> chore: update README with embargoed asset info [DX-63]
